apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: dev
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: app-database
  template:
    metadata:
      labels:
        app: app-database
    spec:
      containers:
      - name: nginx
        image: vamshisuraj/database:dbimage
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      imagePullSecrets:
            - name: dockerhub-secret
  volumeClaimTemplates:
  - metadata:
      name: www
   spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
